name: Python CI

on: [push]

jobs:
  build:
    runs-on: python-stage

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.0-alpha - 3.12.0'

    - name: Install dependencies
      run: |
        python3.12 -m venv venv
        source venv/bin/activate
        pip3.12 install -r requirements.txt
        
    - name: Run server
      run: |
        source venv/bin/activate
        nohup uvicorn app.main:app --host localhost --port 8000 --reload > uvicorn.log 2>&1 &
        sleep 2

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest -v
        
